version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    container_name: db-front
    environment:
      - POSTGRES_USER=userdix
      - POSTGRES_DB=dbdixfront
      - POSTGRES_PASSWORD=dix_app1234
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
    pg-data: